services:
  - type: web
    name: paywise-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET
        generateValue: true
      - key: DEV_ALLOW_ALL
        value: "true"          # bypass subscription for testing
      - key: TEST_EMAIL
        value: test@example.com
    disk:
      name: paywise-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
